### ISSUE TITLE
 why number_of_children = value / PERF_SWEVENT_MAX_FILE?

### ISSUE THREAD

**Issue by ali-zohrevand** [hiikezoe/android_run_root_shell#20]
hi ..
good job brother ...
i am trying to understand your code ...
could you help me ...
in perf_event exploit ..
line 161 
why the resualt of value / PERF_SWEVENT_MAX_FILE is  number_of_children?
thanks

**Comment by hiikezoe** [comment]
Because of the maximum number of open file descriptors per process.

And please comment to appropriate place.
This repository has been moved to https://github.com/android-rooting-tools/android_run_root_shell
Moreover, your question is a question about https://github.com/android-rooting-tools/libperf_event_exploit

Please ask there.

Thank you,

**Comment by ali-zohrevand** [comment]
thanks
